# This file is where you define your pipelines. You can define multiple.
# For more information on multiple pipelines, see the documentation:
#   https://www.elastic.co/guide/en/logstash/current/multiple-pipelines.html
  
- pipeline.id: training
  path.config: "/tmp/datasets/training/training.conf"

- pipeline.id: test
  path.config: "/tmp/datasets/test/test.conf"